<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIgwVirJ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIgwVirJ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIgwVirJ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIgwVirJ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIgwVirJ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IgwVirJ',
    'container.build_id' => '69d64101',
    'container.build_time' => 1522355141,
));
